import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { RightsBadge, formatDate, rightsCopy } from "@/components/DataPrimitives";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Bot, Check, Database, FileClock, Play, RefreshCcw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

export default function Admin() {
  const { user } = useAuth();
  const enabled = user?.role === "admin";
  const overview = trpc.admin.overview.useQuery(undefined, { enabled });
  const sources = trpc.admin.sources.useQuery(undefined, { enabled });
  const reports = trpc.admin.reports.useQuery(undefined, { enabled });
  const runs = trpc.admin.runs.useQuery(undefined, { enabled });
  const automation = trpc.admin.automation.useQuery(undefined, { enabled });
  const utils = trpc.useUtils();
  const updateSource = trpc.admin.updateSource.useMutation({ onSuccess: () => { utils.admin.sources.invalidate(); utils.sources.invalidate(); toast.success("來源政策已更新"); } });
  const generate = trpc.admin.generateDraft.useMutation({ onSuccess: result => { utils.admin.reports.invalidate(); utils.admin.runs.invalidate(); toast.success(result.skipped ? "來源不足，未建立草稿" : "已建立待審草稿"); }, onError: error => toast.error(error.message) });
  const updateReport = trpc.admin.updateReportStatus.useMutation({ onSuccess: () => { utils.admin.reports.invalidate(); utils.reports.invalidate(); toast.success("報導狀態已更新"); } });

  if (user && user.role !== "admin") return <DashboardLayout><div className="mx-auto max-w-2xl py-20"><Alert variant="destructive"><AlertTriangle className="size-4" /><AlertTitle>沒有管理權限</AlertTitle><AlertDescription>此區僅供 PiSuAI 資料治理管理者使用。</AlertDescription></Alert></div></DashboardLayout>;

  return (
    <DashboardLayout>
      <div className="mx-auto max-w-7xl">
        <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">GOVERNANCE CONTROL ROOM</p><h1 className="mt-4 font-serif text-4xl font-semibold">資料治理總覽</h1><p className="mt-3 text-sm text-muted-foreground">管理公開邊界、審核 AI 草稿並保留每一次管線執行的紀錄。</p></div><Button className="rounded-none" onClick={() => generate.mutate()} disabled={generate.isPending}><Bot className="mr-2 size-4" />{generate.isPending ? "生成中…" : "產生一則待審草稿"}</Button></div>
        <div className="mt-9 grid gap-px bg-ink/10 sm:grid-cols-3"><Stat icon={Database} value={overview.data?.sourceStats?.total ?? "—"} label="來源總數" sub={`${Number(overview.data?.sourceStats?.publicCount ?? 0)} 筆公開`} /><Stat icon={FileClock} value={overview.data?.reportStats?.reviewCount ?? "—"} label="待審報導" sub={`${Number(overview.data?.reportStats?.total ?? 0)} 篇總計`} /><Stat icon={RefreshCcw} value={overview.data?.runStats?.total ?? "—"} label="管線執行" sub={`${Number(overview.data?.runStats?.failedCount ?? 0)} 次失敗`} /></div>

        <Tabs defaultValue="sources" className="mt-10">
          <TabsList className="h-auto w-full justify-start rounded-none border-b border-ink/10 bg-transparent p-0"><TabsTrigger value="sources" className="rounded-none px-5 py-3">來源治理</TabsTrigger><TabsTrigger value="reports" className="rounded-none px-5 py-3">報導審核</TabsTrigger><TabsTrigger value="runs" className="rounded-none px-5 py-3">管線紀錄</TabsTrigger><TabsTrigger value="automation" className="rounded-none px-5 py-3">自動化</TabsTrigger></TabsList>
          <TabsContent value="sources" className="mt-6"><div className="overflow-x-auto border border-ink/10 bg-paper"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-navy text-xs tracking-wider text-white/65"><tr><th className="p-4">來源</th><th className="p-4">類別</th><th className="p-4">權利分級</th><th className="p-4">狀態</th><th className="p-4">公開</th><th className="p-4 text-right">操作</th></tr></thead><tbody className="divide-y divide-ink/10">{sources.isLoading ? <tr><td colSpan={6} className="p-4"><Skeleton className="h-24 rounded-none" /></td></tr> : sources.data?.map(source => <tr key={source.id}><td className="p-4"><strong>{source.name}</strong><p className="mt-1 max-w-xs truncate text-xs text-muted-foreground">{source.provider}</p></td><td className="p-4 text-xs">{source.category}</td><td className="p-4"><Select value={source.rightsClass} onValueChange={value => updateSource.mutate({ id: source.id, rightsClass: value as keyof typeof rightsCopy })}><SelectTrigger className="h-9 w-40 rounded-none"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(rightsCopy).map(([key, copy]) => <SelectItem key={key} value={key}>{copy.label}</SelectItem>)}</SelectContent></Select></td><td className="p-4 font-mono text-xs">{source.status}</td><td className="p-4">{source.isPublic ? <span className="text-jade-dark">已公開</span> : <span className="text-muted-foreground">受控</span>}</td><td className="p-4 text-right"><Button size="sm" variant="outline" className="rounded-none" onClick={() => updateSource.mutate({ id: source.id, isPublic: !source.isPublic, status: source.isPublic ? "review" : "active" })}>{source.isPublic ? "移回審查" : "核准公開"}</Button></td></tr>)}</tbody></table></div></TabsContent>
          <TabsContent value="reports" className="mt-6"><div className="space-y-3">{reports.data?.map(report => <div key={report.id} className="grid gap-5 border border-ink/10 bg-paper p-5 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-3"><span className="eyebrow">{report.topic}</span><span className="font-mono text-xs text-muted-foreground">{report.status}</span>{report.generatedBy === "ai-assisted" && <span className="text-xs text-gold-dark"><Bot className="mr-1 inline size-3" />{report.model}</span>}</div><h3 className="mt-3 font-serif text-xl font-semibold">{report.title}</h3><p className="mt-2 text-xs text-muted-foreground">{formatDate(report.createdAt)} · {report.sourceCount} 個來源</p></div><div className="flex gap-2">{report.status !== "published" && <Button size="sm" className="rounded-none" onClick={() => updateReport.mutate({ id: report.id, status: "published", reviewNote: "管理者完成來源與表述審核" })}><Check className="mr-2 size-4" />核准發布</Button>}{report.status === "published" && <Button size="sm" variant="outline" className="rounded-none" onClick={() => updateReport.mutate({ id: report.id, status: "withdrawn", reviewNote: "管理者撤回" })}>撤回</Button>}</div></div>)}{!reports.data?.length && <Empty copy="目前沒有報導草稿" />}</div></TabsContent>
          <TabsContent value="runs" className="mt-6"><div className="border border-ink/10 bg-paper"><div className="divide-y divide-ink/10">{runs.data?.map(({ run, sourceName }) => <div key={run.id} className="grid gap-3 p-5 md:grid-cols-[160px_100px_1fr_160px]"><span className="font-mono text-xs text-muted-foreground">{formatDate(run.startedAt)}</span><span className={`font-mono text-xs ${run.status === "failed" ? "text-red-700" : run.status === "succeeded" ? "text-jade-dark" : "text-muted-foreground"}`}>{run.status}</span><span className="text-sm">{run.message || sourceName || "—"}</span><span className="text-right text-xs text-muted-foreground">{run.trigger} · {run.recordsChanged} changes</span></div>)}</div>{!runs.data?.length && <Empty copy="尚無管線執行紀錄" />}</div></TabsContent>
          <TabsContent value="automation" className="mt-6"><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><div className="border-l-4 border-jade bg-navy p-8 text-white"><div className="flex items-center justify-between"><ShieldCheck className="size-7 text-jade" /><span className={`border px-2 py-1 text-[10px] font-bold ${automation.data?.enabled ? "border-jade/50 text-jade" : "border-white/20 text-white/40"}`}>{automation.data?.enabled ? "ACTIVE" : "PAUSED"}</span></div><h2 className="mt-8 font-serif text-3xl font-semibold">兩日深度報導</h2><p className="mt-4 text-sm leading-7 text-white/58">每 48 小時選取已核准來源，使用 {automation.data?.model || "gpt-5-mini"} 建立具引用的待審草稿。系統不會自動公開。</p><dl className="mt-8 grid grid-cols-2 gap-5 border-t border-white/10 pt-6 text-sm"><div><dt className="text-white/40">排程</dt><dd className="mt-2 font-mono">{automation.data?.cronExpression || "0 0 1 */2 * *"}</dd></div><div><dt className="text-white/40">最近執行</dt><dd className="mt-2">{formatDate(automation.data?.lastRunAt)}</dd></div></dl></div><Alert className="rounded-none border-gold/30 bg-gold/5"><AlertTriangle className="size-4 text-gold-dark" /><AlertTitle>人工發布閘門已鎖定</AlertTitle><AlertDescription className="leading-7">排程端點只可新增 review 狀態草稿。發布、撤回與來源公開狀態只能由管理者操作，所有變更寫入稽核紀錄。</AlertDescription></Alert></div></TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}
function Stat({ icon: Icon, value, label, sub }: { icon: typeof Database; value: string | number; label: string; sub: string }) { return <div className="bg-paper p-6"><Icon className="size-5 text-gold-dark" /><p className="mt-7 font-serif text-4xl font-semibold">{value}</p><p className="mt-2 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{sub}</p></div>; }
function Empty({ copy }: { copy: string }) { return <div className="p-12 text-center text-sm text-muted-foreground">{copy}</div>; }
