export const expandedSources = [
  {
    slug: "mof-fia-open-data",
    name: "財政部財政資訊中心開放資料",
    provider: "財政部財政資訊中心",
    category: "金融、經濟與稅務",
    accessType: "CSV／官方 API",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版；電子發票逐 API 核對",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://data.gov.tw/dataset/9400",
    repoUrl: null,
    commitSha: null,
    updateCadence: "稅籍代表資料集每日；電子發票依各 API",
    description: "財政稅務與營利事業資料入口，代表資料集涵蓋營業地址、統一編號、營業人名稱、資本額、設立日期、組織別與行業代號；電子發票另由官方 ODS API 提供統計及清單型資料。",
    riskNote: "首頁不是單一授權證據；個人獨資與小型營業人可能可被識別。不得推論個人信用、稅務或消費紀錄，並須對電子發票各 API 分別查核授權與保存條件。",
    attribution: "標示財政部財政資訊中心、資料集名稱、版本或查詢日期，附政府資料開放授權條款連結。",
  },
  {
    slug: "cbc-open-data",
    name: "中央銀行資料開放與統計資料庫",
    provider: "中央銀行",
    category: "金融、經濟與稅務",
    accessType: "CSV／官方查詢",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版",
    rightsClass: "A" as const,
    featured: true,
    sourceUrl: "https://www.cbc.gov.tw/tw/lp-1032-1.html",
    repoUrl: null,
    commitSha: null,
    updateCadence: "依資料集每日、每月、每季或不定期",
    description: "中央銀行匯率、貼放利率、金融統計、外匯存底、銀行存放款利率及資產負債統計的官方開放入口。",
    riskNote: "公開再利用限於已明確標示授權的資料資產；央行標誌、特別聲明附件與其他網站素材不在資料授權範圍。引用時保留資料日期與版本。",
    attribution: "標示中央銀行、資料集名稱、資料日期或版本，並附政府資料開放授權條款。",
  },
  {
    slug: "tdx-official-platform",
    name: "TDX 運輸資料流通服務平臺",
    provider: "交通部及各資料來源單位",
    category: "交通、不動產與地理",
    accessType: "OData／Open API",
    codeLicense: "官方 SampleCode 未明示 LICENSE",
    dataLicense: "免審核與需審核資料並存；逐資料集核對",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://tdx.transportdata.tw/",
    repoUrl: "https://github.com/tdxmotc/SampleCode",
    commitSha: "89c3debf626d60de862d3c45d5672564c2116df5",
    updateCadence: "依資料集每分鐘、每日、每週或不定期",
    description: "交通部整合全臺公車、軌道、公路、航空、航運、自行車、路況與停車等動靜態資料的官方 API 平臺。",
    riskNote: "平台包含免審核、需審核、歷史與機敏資料；會員、API 金鑰、額度、收費與保存條件須逐資料集遵守。SampleCode 無明示 LICENSE，不得推定程式可自由再利用。",
    attribution: "清楚標示交通部運輸資料流通服務平臺或實際資料來源單位，並保存 endpoint、更新時間及查詢日期。",
  },
  {
    slug: "moi-real-price-open-data",
    name: "內政部不動產實價登錄 OPEN DATA",
    provider: "內政部地政司",
    category: "交通、不動產與地理",
    accessType: "CSV／XML／XLS／TXT",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版",
    rightsClass: "A" as const,
    featured: true,
    sourceUrl: "https://plvr.land.moi.gov.tw/DownloadOpenData",
    repoUrl: null,
    commitSha: null,
    updateCadence: "每月 1、11、21 日發布",
    description: "全國不動產買賣、預售屋及租賃交易的官方批次資料，可依全國、縣市與交易類型下載。",
    riskNote: "原使用者網址 plam.moi.gov.tw 無法解析，已改用官方 canonical 入口。交易位置、價格與面積等欄位組合具有再識別風險；不得作個人信用、行銷或不當人戶推論。",
    attribution: "標示內政部地政司、發布期別、交易類別及政府資料開放授權條款。",
  },
  {
    slug: "mohw-open-data",
    name: "衛生福利部政府開放資料",
    provider: "衛生福利部及所屬機關",
    category: "公共衛生、醫療與環境",
    accessType: "ODS／CSV／官方 API",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版；逐子平臺與資料集核對",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://dep.mohw.gov.tw/DOS/np-6599-113.html",
    repoUrl: null,
    commitSha: null,
    updateCadence: "依資料集每日、每年或不定期",
    description: "衛福部暨所屬醫事司、疾病管制署與健保署的醫療機構、傳染病統計、健保特約院所及其他公共衛生資料入口。",
    riskNote: "病例資料可能含年齡層、村里與感染地等細粒度欄位，禁止與外部資料任意拼接或作個人醫療風險推斷；非公開防疫次級資料仍須申請。",
    attribution: "逐資料集標示衛福部實際提供單位、年份、資料名稱、版本與政府資料開放授權條款。",
  },
  {
    slug: "moenv-open-data",
    name: "環境部環境資料開放平臺",
    provider: "環境部",
    category: "公共衛生、醫療與環境",
    accessType: "CSV／XML／JSON／API",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版；附件逐資產核對",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://data.moenv.gov.tw/",
    repoUrl: null,
    commitSha: null,
    updateCadence: "依資料集每小時、每月或不定期",
    description: "環境部官方環境資料入口，涵蓋 AQI、空氣品質、水質監測、碳足跡排放係數與廢棄物統計。",
    riskNote: "資料集原始資料通常有明確政府授權，但報告附件、影音、第三方內容與上游網站資產仍須逐件查核；不得以 API 範例推定程式碼授權。",
    attribution: "標示實際提供機關、年份、資料集名稱、版本，並附政府資料開放授權條款。",
  },
  {
    slug: "campaign-finance-digitalization",
    name: "臺灣政治獻金資料數位化專案",
    provider: "ronnywang／g0v 社群；上游監察院",
    category: "公共監督與立法追蹤",
    accessType: "GitHub 歷史資料與程式",
    codeLicense: "README 宣稱 MIT；無 LICENSE 檔",
    dataLicense: "歷史資產未明示；現行監察院資料集另採政府資料授權",
    rightsClass: "MIXED" as const,
    featured: false,
    sourceUrl: "https://ardata.cy.gov.tw/",
    repoUrl: "https://github.com/ronnywang/tw-campaign-finance",
    commitSha: "12d8df0c309cebe146188aebcf02a93d116de99f",
    updateCadence: "2015 年後長期停更",
    description: "2014 至 2015 年間政治獻金資料的社群結構化專案；原 g0v repository 路徑不存在，已校正至 ronnywang 的 canonical repository。",
    riskNote: "涉及捐贈者、支出對象、地址、電話、交易日期與金額等個資及交易明細。只公開專案索引與官方導流，不鏡像原始明細、圖片或附件；須提供更正、申訴與撤下機制。",
    attribution: "程式保留 README 所述 MIT 聲明；資料另標示監察院、資料集年份、版本與官方來源。",
  },
  {
    slug: "taiwan-company-graph",
    name: "台灣公司關係圖",
    provider: "Ronny Wang／g0v；上游經濟部與財政部",
    category: "公司與商業",
    accessType: "公開查詢＋GitHub 程式",
    codeLicense: "README 明示 BSD；無獨立 LICENSE 檔",
    dataLicense: "公司與稅籍資料逐上游資料集核對",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://company-graph.g0v.ronny.tw/",
    repoUrl: "https://github.com/ronnywang/company-graph",
    commitSha: "2e5f6d54c41eb98f02096b262e9a95fe4b062d55",
    updateCadence: "上游公司資料每月；稅籍資料每日",
    description: "將公司、商號、法人與董監事等關係視覺化的公開查詢服務；原 g0v repository 路徑不存在，已校正至 canonical repository。",
    riskNote: "自然人姓名可能同名，關係圖不得被推論為實益控制、不法或政治關係。只公開來源索引與導流，避免批次鏡像自然人關係。",
    attribution: "標示台灣公司關係圖、程式 repository，以及經濟部公司登記與財政部稅籍資料的名稱及版本。",
  },
  {
    slug: "tipo-patent-trademark-open-data",
    name: "智慧財產局專利商標開放資料",
    provider: "經濟部智慧財產局",
    category: "智慧財產與專利訴訟",
    accessType: "FTP／XML／JSON API",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版；附件與第三人權利除外",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://cloud.tipo.gov.tw/S220/opdata/",
    repoUrl: null,
    commitSha: null,
    updateCadence: "依公報與資料集每月多次更新",
    description: "官方專利公開與公告公報、完整說明書、專利權狀態與關聯案件、商標公報及商標權狀態資料入口。",
    riskNote: "發明人、申請人、權利人、代理人及地址等欄位涉及個資；商標圖樣、WAV、掃描附件與舉發事件可能涉及第三人權利及名譽。僅公開索引與欄位級摘要，不重發布敏感附件。",
    attribution: "標示經濟部智慧財產局、資料集名稱、版本或公報發行日，並附政府資料開放授權條款。",
  },
  {
    slug: "judicial-ip-commercial-judgments",
    name: "司法院裁判書開放資料（含智財商業案件）",
    provider: "司法院",
    category: "智慧財產與專利訴訟",
    accessType: "會員資料集／官方 API",
    codeLicense: "不適用",
    dataLicense: "司法院開放資料使用規範及平台授權條款",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://opendata.judicial.gov.tw/dataset?categoryTheme4Sys%5B%5D=051",
    repoUrl: null,
    commitSha: null,
    updateCadence: "裁判書按月打包；API 持續更新",
    description: "司法院按月提供裁判書資料集與 API，欄位包含案號、日期、標題、全文及 PDF；可涵蓋智慧財產及商業法院案件，但院別篩選須依官方欄位核實。",
    riskNote: "只收錄公開可得資訊並公開索引，不鏡像全文或 PDF。裁判含姓名與案件個資，摘要不得作為法律意見或對人的事實定性；不保證資料完全正確，使用者應自行核對並承擔使用風險，且須追蹤更正與撤下。",
    attribution: "標示司法院資料開放平臺、裁判書資料集月份、更新版本與官方連結；不得暗示司法院背書。",
  },
  {
    slug: "legislative-ivod-transcripts",
    name: "立法院議事轉播 IVOD 與發言紀錄",
    provider: "立法院",
    category: "公共監督與立法追蹤",
    accessType: "官方影音與會議頁",
    codeLicense: "使用者指定 GitHub repository 不存在",
    dataLicense: "IVOD 影音限個人非商業使用；逐字與公報逐資產核對",
    rightsClass: "MIXED" as const,
    featured: false,
    sourceUrl: "https://ivod.ly.gov.tw/",
    repoUrl: null,
    commitSha: null,
    updateCadence: "隨立法院會議持續更新",
    description: "立法院官方即時與隨選議事影音、委員會會議及發言紀錄入口。使用者指定的 g0v/ivod-transcript repository 不存在，故不以其作為可用開源工具。",
    riskNote: "影音公開可觀看不等於可重製、改作或營利。政治發言轉錄涉及姓名、言論、名譽與脈絡，必須保留會議、時間戳、來源與更正流程；本站只公開索引與官方導流。",
    attribution: "標示立法院議事轉播 IVOD、會議名稱與日期，並連回原始會議頁。",
  },
  {
    slug: "mofa-treaty-agreement-database",
    name: "中華民國條約協定資料庫",
    provider: "外交部",
    category: "跨境法律與國際協定",
    accessType: "官方網頁查詢／PDF",
    codeLicense: "不適用",
    dataLicense: "外交部政府網站資料開放宣告；附件逐資產核對",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://no06.mofa.gov.tw/mofatreatys/",
    repoUrl: null,
    commitSha: null,
    updateCadence: "不定期",
    description: "外交部官方條約與協定查詢系統，提供名稱、簽署國、簽訂日、主題分類及 PDF 全文，包含投資促進與保障協定。",
    riskNote: "原 laws.mofa.gov.tw 無法解析，已校正至官方資料庫。一般網站開放宣告不當然涵蓋所有條約譯本、第三人內容與附件；公開時保留語言、版本、日期並僅作參考。",
    attribution: "標示外交部中華民國條約協定資料庫、協定名稱、語言、簽署日期及官方文件連結。",
  },
  {
    slug: "consumer-dispute-statistics",
    name: "消費爭議申訴與調解統計",
    provider: "行政院消費者保護會",
    category: "消費者保護與勞資爭議",
    accessType: "官方網頁／PDF 統計",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版",
    rightsClass: "A" as const,
    featured: true,
    sourceUrl: "https://cpc.ey.gov.tw/Page/C116BB7EE606AA23",
    repoUrl: null,
    commitSha: null,
    updateCadence: "年度／不定期",
    description: "各年度與各縣市政府受理第一次申訴、第二次申訴及調解案件的彙總統計，含消費爭議類別、件數、比例與年度比較。",
    riskNote: "目前資料為彙總統計，不得以申訴件數推論特定業者違法、裁罰或司法責任；若未來附件含個案或可識別資料，須先去識別並逐資產審查。",
    attribution: "標示行政院消費者保護會、報告年度、完整資料名稱及政府資料開放授權條款。",
  },
  {
    slug: "mol-labor-law-violations",
    name: "違反勞動法令事業單位查詢",
    provider: "勞動部及職業安全衛生署",
    category: "消費者保護與勞資爭議",
    accessType: "官方查詢／CSV／JSON／XML",
    codeLicense: "不適用",
    dataLicense: "政府資料開放授權條款第 1 版",
    rightsClass: "MIXED" as const,
    featured: true,
    sourceUrl: "https://announcement.mol.gov.tw/",
    repoUrl: null,
    commitSha: null,
    updateCadence: "勞基法不定期；職安每日",
    description: "勞動部官方裁罰公告查詢，涵蓋勞動基準法、最低工資法、性別平等工作法及職業安全衛生法，並提供主管機關、處分字號、法條與違反內容。",
    riskNote: "資料含事業單位與負責人姓名，涉及個資及名譽。裁罰紀錄不得被解讀為終局司法認定或全面信用評等；本站只公開來源索引與官方導流，須追蹤更正、申訴及撤下。",
    attribution: "標示勞動部或職安署、資料集名稱、處分日期、資料版本及政府資料開放授權條款。",
  },
] as const;
