export const governmentSpecializedSources = [
  {
    slug: "moj-national-law-api", name: "全國法規資料庫資料下載與 API", provider: "法務部", category: "政府專業資料平臺", accessType: "JSON／XML ZIP API", codeLicense: "不適用", dataLicense: "政府資料開放授權條款第 1 版；法規文字以主管機關公布為準", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://law.moj.gov.tw/Service/LawData.aspx", repoUrl: null, commitSha: null, updateCadence: "每週五整編；當週異動通常於次週更新",
    description: "涵蓋中央法規、行政規則、英文法規與命令的官方整批 JSON／XML 下載入口，並附 schema。",
    riskNote: "法規資料庫是整編查詢服務，不能取代主管機關依法發布的原文；地方規章與跨機關資料可能有同步差。應保留法規版本、公布日、施行日與查詢日期。",
    attribution: "標示全國法規資料庫、法規名稱、版本日期與主管機關；必要時連回主管機關公報。",
  },
  {
    slug: "nhi-open-data-api", name: "全民健康保險資料開放服務", provider: "中央健康保險署", category: "政府專業資料平臺", accessType: "Metadata API／JSON／CSV／XML", codeLicense: "不適用", dataLicense: "政府資料開放授權條款第 1 版；逐資料集核對", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://info.nhi.gov.tw/IODE0000/IODE0000S01", repoUrl: null, commitSha: null, updateCadence: "依資料集每日、每月或不定期",
    description: "健保署官方資料目錄與 API，涵蓋承保、醫務管理、醫療品質、藥品醫材、特約院所及統計資料。",
    riskNote: "僅能收錄已公開、去識別或彙總資料。不得與外部資料拼接進行個人醫療推論、保險風險評分或差別待遇；資料資源 API 有單次筆數限制。",
    attribution: "標示中央健康保險署、資料集 identifier、更新日期及官方授權。",
  },
  {
    slug: "fsc-statistics-api", name: "金融監督管理委員會統計資料 API", provider: "金融監督管理委員會", category: "政府專業資料平臺", accessType: "公開 REST API／匯出", codeLicense: "不適用", dataLicense: "逐資料集核對；API 規格未統一填載授權欄", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://www.fsc.gov.tw/ch/home.jsp?id=1223&parentpath=0,7", repoUrl: null, commitSha: null, updateCadence: "依各金融統計資料集",
    description: "金管會及所屬銀行局、證期局、保險局等金融統計資料與公開 API 入口，可查資料集摘要、schema、資料列及匯出。",
    riskNote: "統計資料不得被誤用為個別金融機構信用評等、投資建議或主管機關背書。API 授權與輸出容量未在 OAS 統一說明，須逐資料集保存條件。",
    attribution: "標示金融監督管理委員會或實際所屬機關、資料集 UUID／alias、資料期間及查詢日期。",
  },
  {
    slug: "dgbas-national-statistics", name: "行政院主計總處統計資料庫", provider: "行政院主計總處", category: "政府專業資料平臺", accessType: "互動查詢／CSV／JSON／XML／PXFile", codeLicense: "不適用", dataLicense: "政府資料開放授權條款第 1 版；逐表保存來源", rightsClass: "A" as const, featured: true,
    sourceUrl: "https://nstatdb.dgbas.gov.tw/dgbasall/webMain.aspx", repoUrl: null, commitSha: null, updateCadence: "依統計表與發布週期",
    description: "國家統計資料庫入口，可依統計表、期間及欄位查詢並輸出多種機器可讀格式，涵蓋人口、家庭、產業、勞動與經濟統計。",
    riskNote: "不同統計表的定義、基期、單位、缺值碼與修訂政策不同；公開衍生分析必須保留表號、期間、單位與查詢條件。",
    attribution: "標示行政院主計總處、統計表名稱與表號、期間、單位及取得日期。",
  },
  {
    slug: "nlsc-map-service-cloud", name: "國土測繪圖資服務雲開放 API", provider: "內政部國土測繪中心", category: "政府專業資料平臺", accessType: "OGC WMS／WMTS／WFS／官方 API", codeLicense: "不適用", dataLicense: "免申請、需申請與付費服務並存", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://maps.nlsc.gov.tw/S09SOA/homePage.action?Language=ZH", repoUrl: null, commitSha: null, updateCadence: "依圖層與服務公告",
    description: "全國基礎圖資、行政界、門牌、地標、地籍相關及 OGC 圖層服務的官方入口。",
    riskNote: "地籍圖磚、地籍 API、模糊檢索與部分圖資可能需申請或付費；免申請清單也可能改版。不得把展示圖層當成法定界址或地籍證明。",
    attribution: "標示內政部國土測繪中心、圖層或服務代碼、版本與使用日期。",
  },
  {
    slug: "pcc-public-construction-api", name: "公共工程雲 Open API", provider: "行政院公共工程委員會", category: "政府專業資料平臺", accessType: "官方 OAS／API", codeLicense: "不適用", dataLicense: "政府資料開放授權條款第 1 版；服務逐端點核對", rightsClass: "MIXED" as const, featured: false,
    sourceUrl: "https://pcic.pcc.gov.tw/pwc-web/service/api001", repoUrl: null, commitSha: null, updateCadence: "依服務公告",
    description: "公共工程雲官方 API 服務入口，涵蓋工程管理、價格與技術服務；目前公開 OAS 不等同完整政府採購標案查詢 API。",
    riskNote: "不得把第三方政府採購鏡像冒充官方 API。標案、附件、廠商、負責人與爭議資訊須另行處理個資、名譽、著作權及撤下更正。",
    attribution: "標示公共工程委員會、官方服務名稱、端點與查詢日期。",
  },
  {
    slug: "taipei-open-data", name: "臺北市資料大平臺", provider: "臺北市政府", category: "地方政府資料平臺", accessType: "資料目錄／API／資源下載", codeLicense: "不適用", dataLicense: "逐資料集保存原授權與顯名要求", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://data.taipei/", repoUrl: null, commitSha: null, updateCadence: "依市府各機關資料集",
    description: "臺北市政府跨局處開放資料目錄、API 預覽與資源下載入口；PiSuAI 以 data.gov.tw 作全國別名並保留臺北原生 UUID。",
    riskNote: "中央與地方目錄可能有同步時間差；同一資料集不可因 UUID、格式或資源 URL 不同而重複計數。",
    attribution: "標示臺北市政府實際提供局處、資料集 UUID、版本與原始頁。",
  },
  {
    slug: "new-taipei-open-data", name: "新北市政府資料開放平臺", provider: "新北市政府", category: "地方政府資料平臺", accessType: "OpenAPI／JSON／CSV／XML", codeLicense: "不適用", dataLicense: "政府資料開放授權條款第 1 版；逐資料集核對", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://data.ntpc.gov.tw/", repoUrl: null, commitSha: null, updateCadence: "依市府各機關資料集",
    description: "新北市政府跨機關資料目錄與 OpenAPI，提供 unit 規格及資料集 UUID 的分頁查詢。",
    riskNote: "原生 UUID 與中央 datasetId 應建立同源關聯，不以標題直接合併；未公告的速率及最大容量需保守處理。",
    attribution: "標示新北市政府實際提供機關、資料集 UUID、格式與查詢日期。",
  },
  {
    slug: "taoyuan-open-data", name: "桃園市政府資料開放平臺", provider: "桃園市政府", category: "地方政府資料平臺", accessType: "Metadata API／datastore", codeLicense: "不適用", dataLicense: "逐資料集保存原授權", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://opendata.tycg.gov.tw/", repoUrl: null, commitSha: null, updateCadence: "依市府各機關資料集",
    description: "桃園市政府資料集搜尋、詳細資訊、資源資訊及 datastore API 入口，具有分頁與 offset 查詢能力。",
    riskNote: "metadata 與內容 API 應分離；只同步資料集資訊，不高頻掃描 datastore 原始內容。中央與地方版本須保留 provenance。",
    attribution: "標示桃園市政府實際提供機關、pid／rid、更新日期與原授權。",
  },
  {
    slug: "taichung-open-data", name: "臺中市政府資料開放平臺", provider: "臺中市政府", category: "地方政府資料平臺", accessType: "目錄／OAS／API", codeLicense: "不適用", dataLicense: "逐資料集保存原授權", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://opendata.taichung.gov.tw/", repoUrl: null, commitSha: null, updateCadence: "依市府各機關資料集",
    description: "臺中市政府跨局處資料集、API services 與 Swagger／OAS 入口。",
    riskNote: "資料集數與 API service 數不能相加；同一資料集多端點、多格式應視為 distributions，而非多筆資料集。",
    attribution: "標示臺中市政府實際提供機關、資料集或 API 服務識別資訊與版本。",
  },
  {
    slug: "tainan-open-data", name: "臺南市政府資料開放平臺", provider: "臺南市政府", category: "地方政府資料平臺", accessType: "資料清冊／CSV／JSON", codeLicense: "不適用", dataLicense: "逐資料集及外部來源核對", rightsClass: "MIXED" as const, featured: true,
    sourceUrl: "https://data.tainan.gov.tw/", repoUrl: null, commitSha: null, updateCadence: "依市府各機關資料集",
    description: "臺南市政府開放資料目錄與資料清冊；部分資料資源實際來自 TDX 或民生公共物聯網。",
    riskNote: "外部來源只建立同源關聯，不重複抓取或重複計數；須遵守 TDX、物聯網平臺等實際上游條件。",
    attribution: "標示臺南市政府實際提供機關及外部資料來源、資料集版本與查詢日期。",
  },
  {
    slug: "kaohsiung-open-data", name: "高雄市政府資料開放平臺", provider: "高雄市政府", category: "地方政府資料平臺", accessType: "資料目錄／城市資料服務", codeLicense: "不適用", dataLicense: "逐資料集核對；部分 API 規格待重新驗證", rightsClass: "B" as const, featured: false,
    sourceUrl: "https://data.kcg.gov.tw/", repoUrl: null, commitSha: null, updateCadence: "依市府各機關資料集",
    description: "高雄市政府官方開放資料入口；全國目錄已收錄高雄市資料，原生 API 與服務規格另行驗證。",
    riskNote: "本次查核環境無法穩定解析官方原生頁面，因此先公開來源索引與全國目錄別名，不宣稱已完成原生 API 同步。",
    attribution: "標示高雄市政府實際提供機關、data.gov.tw datasetId 與官方原生入口。",
  },
] as const;
